---
- hosts: all
  name: Execute pgd_bench - benchmark
  gather_facts: false
  become: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Load servers.yml
      ansible.builtin.include_vars:
        file: "{{ terraform_project_path }}/servers.yml"
        name: infra

    - name: Display keys and values
      debug:
        msg: "{{ node.key }}: {{ node.value }}"
        msg: "{{ node.key }}"
      loop: "{{ infra.servers.machines | dict2items }}"
      loop_control:
        loop_var: node
      when: node.key == 'pgd1'

    - name: Initialize pgd_bench prior to benchmark
      ansible.builtin.shell: |
        ./pgd_bench -h {{ node.key }} -p {{ pg_port }} -i {{ pg_database }} -s {{ pgd_bench_scale_factor }}
      args:
        chdir: "{{ pgd_bench_home }}"        
      become_user: "{{ pg_owner }}"
      loop: "{{ infra.servers.machines | dict2items }}"
      loop_control:
        loop_var: node
      when: node.key == 'pgd1'

    - name: Execute pgd_bench benchmark
      ansible.builtin.shell: |
        {{ pgd_bench_home }}/pgd_bench -T {{ pgd_bench_duration }} -c {{ pgd_bench_clients }} -N -m camo -h {{ node.key }} -p {{ pg_port }} {{ pg_database }} {{ node.key }}
      args:
        chdir: "{{ pgd_bench_home }}"
      become_user: "{{ pg_owner }}"        
      loop: "{{ infra.servers.machines | dict2items }}"
      loop_control:
        loop_var: node
      when: node.key == 'pgd1'

    # - name: Fetch data files
    #   ansible.builtin.fetch:
    #     src: "/home/{{ hammerdb_user }}/{{ item }}"
    #     dest: "{{ results_directory }}/{{ item }}"
    #     flat: true
    #   loop:
    #   - "pgd_nopm_catchup_time.csv"
