---
- hosts: dbt2_driver
  name: Populate DBT2 database
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  tasks:
    - name: Populate DBT2 database
      ansible.builtin.command:
        cmd: >-
         dbt2 build --db-port={{ pg_port }} --warehouses={{ dbt2_warehouse }}
         pgsql
      become_user: "{{ pg_owner }}"
      changed_when: false
      register: result

    - name: Database build output
      ansible.builtin.debug:
        var: result
