---
- hosts: dbt2_driver
  name: Install repository
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        enable_edb_repo: false

  roles:
    - role: setup_repo

- hosts: dbt2_driver
  name: Install DBT2 driver
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  roles:
    - setup_dbt2_driver
    - setup_touchstone_tools

  tasks:
    - name: Update .pgpass
      ansible.builtin.lineinfile:
        path: "{{ pg_user_home }}/.pgpass"
        regexp: ^\*:[^\n]+:\*:{{ pg_owner }}.*
        line: "*:*:*:{{ pg_owner }}:{{ pg_password }}"
        owner: "{{ pg_owner }}"
        group: "{{ pg_group }}"
        mode: "0600"
      become: true
